image: atlassian/default-image:5

definitions:
  caches:
    node: /usr/local/share/.cache/yarn/v6
    npm: ~/.npm

pipelines:
  default:
    - step: &build-application
        name: Build application
        caches:
          - node
          - npm
        script:
          - npm ci
          - npm run build
        artifacts:
          - dist/**

    - step: &run-tests
        name: Run tests
        caches:
          - node
          - npm
        script:
          - npm ci
          - apt-get install -y apt-get install -y \
            fonts-liberation \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libatspi2.0-0 \
            libcups2 \
            libdbus-1-3 \
            libdrm2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libwayland-client0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxkbcommon0 \
            libxrandr2 \
            xdg-utils \
            libu2f-udev \
            libvulkan1
          - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          - apt-get install -y ./google-chrome-stable_current_amd64.deb
          - npm run test
        artifacts:
          - coverage/**

  branches:
    master:
      - step: *build-application
      - step: *run-tests

options:
  max-time: 1

docker:
  services:
    docker:
      memory: 4096
