image: node:20.19.0

definitions:
  caches:
    node: /usr/local/share/.cache/yarn/v6

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - node
        script:
          - npm ci

    - step:
        name: Build application
        caches:
          - node
        script:
          - ng build
        artifacts:
          - dist/**

    - step:
        name: Run tests
        caches:
          - node
        script:
          - ng test --no-watch --no-progress --browsers=ChromeHeadless
        artifacts:
          - coverage/**


options:
  max-time: 3
  size: 2x
