image: atlassian/default-image:5

definitions:
  caches:
    node: /usr/local/share/.cache/yarn/v6
    npm: ~/.npm

pipelines:
  default:
    - step: &build-application
        name: Build application
        caches:
          - node
          - npm
        script:
          - npm ci
          - npm run build
        artifacts:
          - dist/**

    - step: &run-tests
        name: Run tests
        caches:
          - node
          - npm
        script:
          - npm ci
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
            apt-get update
            apt-get install -y google-chrome-stable xvfb
          - npm run test
        artifacts:
          - coverage/**

  branches:
    master:
      - step: *build-application
      - step: *run-tests

options:
  max-time: 1

docker:
  services:
    docker:
      memory: 4096
