image: node:20.19.0

definitions:
  caches:
    node: /usr/local/share/.cache/yarn/v6
    npm: ~/.npm

pipelines:
  default:
#    - step: &install-dependencies
#        name: Install dependencies
#        caches:
#          - node
#          - npm
#        script:
#          - npm ci
#          - npm install -D @angular/cli
#          - npx ng version

    - step: &build-application
        name: Build application
        caches:
          - node
          - npm
        script:
          - npm ci
          - npm install -D @angular/cli
          - npm run build
        artifacts:
          - dist/**

    - step: &run-tests
        name: Run tests
        caches:
          - node
          - npm
        script:
          - npm run test
        artifacts:
          - coverage/**

  branches:
    master:
#      - step: *install-dependencies
      - step: *build-application
      - step: *run-tests

options:
  max-time: 1

docker:
  services:
    docker:
      memory: 4096
