image: atlassian/default-image:5

definitions:
  caches:
    node: /usr/local/share/.cache/yarn/v6
    npm: ~/.npm

pipelines:
  default:
    - step: &build-application
        name: Build application
        caches:
          - node
          - npm
        script:
          - npm ci
          - npm run build
        artifacts:
          - dist/**

    - step: &run-tests
        name: Run tests
        caches:
          - node
          - npm
        script:
          - npm ci
          # Install the dependencies required for Chrome before installing Chrome itself
          - apt-get install -y --no-install-recommends \
            fonts-liberation \
            libappindicator3-1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgconf-2-4 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            libdrm-dev \
            libgbm-dev

          # Download the latest Google Chrome stable .deb package
          - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/google-chrome-stable_current_amd64.deb

          # Install the .deb package. `dpkg -i` will handle installation.
          - dpkg -i /tmp/google-chrome-stable_current_amd64.deb || apt-get install -fy # Use -fy to fix missing dependencies after dpkg

          # Clean up the downloaded .deb file
          - rm /tmp/google-chrome-stable_current_amd64.deb
          - export CHROME_BIN=/usr/bin/google-chrome
          - npm run test
        artifacts:
          - coverage/**

  branches:
    master:
      - step: *build-application
      - step: *run-tests

options:
  max-time: 1

docker:
  services:
    docker:
      memory: 4096
