image: trion/ng-cli-karma:latest

definitions:
  caches:
    node: /usr/local/share/.cache/yarn/v6
    npm: ~/.npm

pipelines:
  default:
    - step: &build-application
        name: Build application
        caches:
          - node
          - npm
        script:
          - npm ci
          - npm run build
        artifacts:
          - dist/**

    - step: &run-tests
        name: Run tests
        caches:
          - node
          - npm
        script:
          - npm ci
          - timeout 60 npm run test || exit 0
        artifacts:
          - coverage/**

  branches:
    master:
      - step: *build-application
      - step: *run-tests

options:
  max-time: 2
